spring:
  application:
    name: hashtaglocal-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

management:
  health:
    diskspace:
      enabled: false
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    display-request-duration: true
  show-actuator: true
  paths-to-match:
    - /**
    - /actuator/**
  write-operation-modes: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json