spring:
  application:
    name: hashtaglocal-backend
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://localhost:5432/hashtaglocal
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.smalltech.hashtaglocal_backend: DEBUG
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10

# Application-specific custom configuration
app:
  geo:
    verify-radius-meters: 50
  storage:
    bucket-name: hashtaglocalbucket

# Google Maps API configuration
google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY:}
  oauth:
    client-id: ${GOOGLE_OAUTH_CLIENT_ID:}
    client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET:}
    redirect-uri: ${GOOGLE_OAUTH_REDIRECT_URI:}

management:
  health:
    diskspace:
      enabled: false
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    display-request-duration: true
  show-actuator: true
  paths-to-match:
    - /**
    - /actuator/**
  write-operation-modes: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Google Cloud Storage Configuration
gcs:
  credentials:
    path: gcs-key.json
  project:
    id: ${GCS_PROJECT_ID:}


geonames:
  username: ${GEONAMES_USERNAME:mmk1}

auth:
  access-token:
    expiry-seconds: ${AUTH_ACCESS_TOKEN_EXPIRY_SECONDS:10}
  refresh-token:
    expiry-seconds: ${AUTH_REFRESH_TOKEN_EXPIRY_SECONDS:30}