package org.smalltech.hashtaglocal_backend.service;

import com.google.cloud.storage.BlobInfo;
import com.google.cloud.storage.HttpMethod;
import com.google.cloud.storage.Storage;
import java.net.URL;
import java.time.Instant;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;
import org.smalltech.hashtaglocal_backend.config.CustomProperties;
import org.springframework.stereotype.Service;

@Service
public class GCSService {

  private final Storage storage;
  private final String bucketName;
  private static final long SIGNED_URL_DURATION_MINUTES = 60;
  private static final long CACHE_TTL_SECONDS = 55 * 60; // 5 min buffer before URL expiry

  private record CachedUrl(String url, Instant expiresAt) {
    boolean isValid() {
      return Instant.now().isBefore(expiresAt);
    }
  }

  private final ConcurrentHashMap<String, CachedUrl> urlCache = new ConcurrentHashMap<>();

  public GCSService(Storage storage, CustomProperties.Google googleProperties) {
    this.storage = storage;
    this.bucketName = googleProperties.getStorage().getBucketName();
  }

  /**
   * Generates a signed URL for a given GCS path.
   *
   * @param gcsPath the GCS path in format "gs://bucket-name/object-path" or just "object-path"
   * @return a signed URL string
   */
  public String generateSignedUrl(String gcsPath) {
    String objectPath = extractObjectPath(gcsPath);
    String cacheKey = "main:" + objectPath;
    CachedUrl cached = urlCache.get(cacheKey);
    if (cached != null && cached.isValid()) return cached.url();

    BlobInfo blobInfo = BlobInfo.newBuilder(bucketName, objectPath).build();
    URL signedUrl =
        storage.signUrl(
            blobInfo,
            SIGNED_URL_DURATION_MINUTES,
            TimeUnit.MINUTES,
            Storage.SignUrlOption.httpMethod(HttpMethod.GET),
            Storage.SignUrlOption.withV4Signature());

    String url = signedUrl.toString();
    urlCache.put(cacheKey, new CachedUrl(url, Instant.now().plusSeconds(CACHE_TTL_SECONDS)));
    return url;
  }

  /**
   * Generates a signed URL for the optimised (800px) version of a given GCS image path. The
   * optimised image is expected at optimised/{filename} in the same bucket.
   *
   * @param gcsPath the GCS path of the original image
   * @return a signed URL string for the optimised image
   */
  public String generateOptimisedUrl(String gcsPath) {
    String objectPath = extractObjectPath(gcsPath);
    String filename =
        objectPath.contains("/")
            ? objectPath.substring(objectPath.lastIndexOf('/') + 1)
            : objectPath;
    String optimisedPath = "optimised/" + filename;
    String cacheKey = "optimised:" + optimisedPath;
    CachedUrl cached = urlCache.get(cacheKey);
    if (cached != null && cached.isValid()) return cached.url();

    BlobInfo blobInfo = BlobInfo.newBuilder(bucketName, optimisedPath).build();
    URL signedUrl =
        storage.signUrl(
            blobInfo,
            SIGNED_URL_DURATION_MINUTES,
            TimeUnit.MINUTES,
            Storage.SignUrlOption.httpMethod(HttpMethod.GET),
            Storage.SignUrlOption.withV4Signature());

    String url = signedUrl.toString();
    urlCache.put(cacheKey, new CachedUrl(url, Instant.now().plusSeconds(CACHE_TTL_SECONDS)));
    return url;
  }

  /**
   * Generates a signed URL for the thumbnail version of a given GCS image path. The thumbnail is
   * expected at thumbnails/{filename} in the same bucket, generated by the GCP Cloud Function.
   *
   * @param gcsPath the GCS path of the original image
   * @return a signed URL string for the thumbnail
   */
  public String generateThumbnailUrl(String gcsPath) {
    String objectPath = extractObjectPath(gcsPath);
    String filename =
        objectPath.contains("/")
            ? objectPath.substring(objectPath.lastIndexOf('/') + 1)
            : objectPath;
    String thumbnailPath = "thumbnails/" + filename;
    String cacheKey = "thumbnail:" + thumbnailPath;
    CachedUrl cached = urlCache.get(cacheKey);
    if (cached != null && cached.isValid()) return cached.url();

    BlobInfo blobInfo = BlobInfo.newBuilder(bucketName, thumbnailPath).build();
    URL signedUrl =
        storage.signUrl(
            blobInfo,
            SIGNED_URL_DURATION_MINUTES,
            TimeUnit.MINUTES,
            Storage.SignUrlOption.httpMethod(HttpMethod.GET),
            Storage.SignUrlOption.withV4Signature());

    String url = signedUrl.toString();
    urlCache.put(cacheKey, new CachedUrl(url, Instant.now().plusSeconds(CACHE_TTL_SECONDS)));
    return url;
  }

  /**
   * Extracts the object path from a GCS path.
   *
   * @param gcsPath the GCS path in format "gs://bucket-name/object-path" or just "object-path"
   * @return the object path
   */
  private String extractObjectPath(String gcsPath) {
    if (gcsPath == null || gcsPath.isEmpty()) {
      throw new IllegalArgumentException("GCS path cannot be null or empty");
    }

    // If path starts with gs://, extract the object path
    if (gcsPath.startsWith("gs://")) {
      // Format: gs://bucket-name/object-path
      String withoutScheme = gcsPath.substring(5); // Remove "gs://"
      int slashIndex = withoutScheme.indexOf('/');
      if (slashIndex > 0) {
        return withoutScheme.substring(slashIndex + 1); // Return object-path
      }
    }

    // Otherwise assume it's already the object path
    return gcsPath;
  }

  /** Deletes an object from GCS by its gs:// path or bare object name. */
  public void deleteObject(String gcsPath) {
    storage.delete(bucketName, extractObjectPath(gcsPath));
  }

  /** Uploads content to the configured GCS bucket and returns the gs:// path. */
  public String uploadObject(String objectName, byte[] data, String contentType) {
    if (objectName == null || objectName.isBlank()) {
      throw new IllegalArgumentException("objectName cannot be null or blank");
    }

    if (data == null || data.length == 0) {
      throw new IllegalArgumentException("data cannot be null or empty");
    }

    String sanitizedContentType =
        contentType == null || contentType.isBlank() ? "application/octet-stream" : contentType;

    BlobInfo blobInfo =
        BlobInfo.newBuilder(bucketName, objectName).setContentType(sanitizedContentType).build();
    storage.create(blobInfo, data);
    return "gs://" + bucketName + "/" + objectName;
  }
}
