package org.smalltech.hashtaglocal_backend.service;

import com.google.cloud.storage.BlobInfo;
import com.google.cloud.storage.HttpMethod;
import com.google.cloud.storage.Storage;
import java.net.URL;
import java.util.concurrent.TimeUnit;
import org.smalltech.hashtaglocal_backend.config.CustomProperties;
import org.springframework.stereotype.Service;

@Service
public class GCSService {

  private final Storage storage;
  private final String bucketName;
  private static final long SIGNED_URL_DURATION_MINUTES = 60;

  public GCSService(Storage storage, CustomProperties.Google googleProperties) {
    this.storage = storage;
    this.bucketName = googleProperties.getStorage().getBucketName();
  }

  /**
   * Generates a signed URL for a given GCS path.
   *
   * @param gcsPath the GCS path in format "gs://bucket-name/object-path" or just "object-path"
   * @return a signed URL string
   */
  public String generateSignedUrl(String gcsPath) {
    String objectPath = extractObjectPath(gcsPath);

    BlobInfo blobInfo = BlobInfo.newBuilder(bucketName, objectPath).build();

    URL signedUrl =
        storage.signUrl(
            blobInfo,
            SIGNED_URL_DURATION_MINUTES,
            TimeUnit.MINUTES,
            Storage.SignUrlOption.httpMethod(HttpMethod.GET),
            Storage.SignUrlOption.withV4Signature());

    return signedUrl.toString();
  }

  /**
   * Generates a signed URL for the thumbnail version of a given GCS image path. The thumbnail is
   * expected at thumbnails/{filename} in the same bucket, generated by the GCP Cloud Function.
   *
   * @param gcsPath the GCS path of the original image
   * @return a signed URL string for the thumbnail
   */
  public String generateThumbnailUrl(String gcsPath) {
    String objectPath = extractObjectPath(gcsPath);

    // Extract just the filename from the object path (e.g., "image/2024-01-01.jpg"
    // -> "2024-01-01.jpg")
    String filename =
        objectPath.contains("/")
            ? objectPath.substring(objectPath.lastIndexOf('/') + 1)
            : objectPath;
    String thumbnailPath = "thumbnails/" + filename;

    BlobInfo blobInfo = BlobInfo.newBuilder(bucketName, thumbnailPath).build();

    URL signedUrl =
        storage.signUrl(
            blobInfo,
            SIGNED_URL_DURATION_MINUTES,
            TimeUnit.MINUTES,
            Storage.SignUrlOption.httpMethod(HttpMethod.GET),
            Storage.SignUrlOption.withV4Signature());

    return signedUrl.toString();
  }

  /**
   * Extracts the object path from a GCS path.
   *
   * @param gcsPath the GCS path in format "gs://bucket-name/object-path" or just "object-path"
   * @return the object path
   */
  private String extractObjectPath(String gcsPath) {
    if (gcsPath == null || gcsPath.isEmpty()) {
      throw new IllegalArgumentException("GCS path cannot be null or empty");
    }

    // If path starts with gs://, extract the object path
    if (gcsPath.startsWith("gs://")) {
      // Format: gs://bucket-name/object-path
      String withoutScheme = gcsPath.substring(5); // Remove "gs://"
      int slashIndex = withoutScheme.indexOf('/');
      if (slashIndex > 0) {
        return withoutScheme.substring(slashIndex + 1); // Return object-path
      }
    }

    // Otherwise assume it's already the object path
    return gcsPath;
  }

  /** Uploads content to the configured GCS bucket and returns the gs:// path. */
  public String uploadObject(String objectName, byte[] data, String contentType) {
    if (objectName == null || objectName.isBlank()) {
      throw new IllegalArgumentException("objectName cannot be null or blank");
    }

    if (data == null || data.length == 0) {
      throw new IllegalArgumentException("data cannot be null or empty");
    }

    String sanitizedContentType =
        contentType == null || contentType.isBlank() ? "application/octet-stream" : contentType;

    BlobInfo blobInfo =
        BlobInfo.newBuilder(bucketName, objectName).setContentType(sanitizedContentType).build();
    storage.create(blobInfo, data);
    return "gs://" + bucketName + "/" + objectName;
  }
}
